project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - ImmPort.qmd
execute:
  freeze: true
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Thanks for Investigating"
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "OLS vs. TRU-OLS - SDY3080"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - text: "About"
        href: index.qmd  
      - text: "Walk-through"
        menu:
          - text: "ImmPort"
            href: ImmPort.qmd   
    right:
    - icon: youtube
      href: https://www.youtube.com/@CytometryInR
      aria-label: YouTube
    - icon: github
      href: https://github.com/UMGCCCFCSR/SDY3080
      aria-label: GitHub
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: |
    ![AGPL-3.0](/images/AGPL3.png)
    ![CC-BY-SA](/images/CCBYSA.png)
format:
  html:
    css: styles.css

