---
title: "Luciernaga Integration"
format: html
---

```{r}
#devtools::document("/home/david/Documents/Luciernaga")
#devtools::load_all("/home/david/Documents/Luciernaga")
```

```{r}
library(dplyr)
library(purrr)
library(flowWorkspace)
library(Luciernaga)
```


# Cell Single-Colors

```{r}
CellsSC_GatingSet <- load_gs("outputs/CellsSC_GS2_Amplified.gs")

# plot(CellsSC_GatingSet)

Template <- pData(CellsSC_GatingSet)
Template <- Template |> mutate(Detector="", Negative="CellUnstained")

Template <- Template |> mutate(
    Detector = map_chr(Fluorophore, \(f) DetectorGuess(x = f, NumberDetectors = 64))
  )

KeptCells <- Template |>
     filter(!name %in% "DTR_2023_ILT_01-Reference Group-DR_Dump_CD19 Pacific Blue (Cells).1235702.fcs") |>
     filter(!name %in% "DTR_2023_ILT_01-Reference Group-DR_Viability_PMA Zombie NIR (Cells).1235709.fcs") |>
     filter(!name %in% "DTR_2023_ILT_01-Reference Group-DR_CD3 Alexa Fluor 488 (Cells).1235688.fcs") 

# View(KeptCells)
# plot(CellsSC_GatingSet)
```

```{r}
LuciernagaIntegration(template=KeptCells[1,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[2,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[3,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[4,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
#| eval: FALSE
LuciernagaIntegration(template=KeptCells[5,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
#| eval: FALSE
# Bugged
LuciernagaIntegration(template=KeptCells[6,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[7,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[8,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[9,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[10,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
#| eval: FALSE
# bugged
LuciernagaIntegration(template=KeptCells[11,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
#| eval: FALSE
# bugged
LuciernagaIntegration(template=KeptCells[12,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[13,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[14,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[15,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
#| eval: FALSE
# bugged
LuciernagaIntegration(template=KeptCells[16,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[17,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[18,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[19,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[20,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[21,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```
```{r}
LuciernagaIntegration(template=KeptCells[22,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```
```{r}
#| eval: FALSE
# bugged
LuciernagaIntegration(template=KeptCells[23,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[24,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```
```{r}
LuciernagaIntegration(template=KeptCells[25,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```
```{r}
LuciernagaIntegration(template=KeptCells[26,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```
```{r}
LuciernagaIntegration(template=KeptCells[27,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[28,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
LuciernagaIntegration(template=KeptCells[29,], gs=CellsSC_GatingSet, GuessSimilar=TRUE)
```

```{r}
Unstained_GatingSet <- load_gs("outputs/CellsUnstained_GS.gs")
Updated <- pData(Unstained_GatingSet) |>  mutate(Type="Cells", Fluorophore="scatter",
 Antigen="Autofluorescence", Detector="V7", Negative="NoSubtraction")
#pData(Unstained_GatingSet) <- Updated

LuciernagaIntegration(template=Updated[1,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[2,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[3,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[4,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[5,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[6,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[7,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[8,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[9,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[10,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```

```{r}
LuciernagaIntegration(template=Updated[11,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```


```{r}
LuciernagaIntegration(template=Updated[12,], gs=Unstained_GatingSet, GuessSimilar=FALSE,
  Unstained=TRUE, inverse.transform=FALSE)
```


```{r}
print("Goodbye")
```
